# Generated by Django 5.0.1 on 2024-01-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stockid', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('stockname', models.TextField()),
                ('stockqty', models.IntegerField()),
            ],
        ),
    ]
