# Generated by Django 5.0.1 on 2024-01-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplierid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('suppliername', models.TextField()),
                ('supplierphonenum', models.CharField(max_length=12)),
                ('supplieremail', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
