# Generated by Django 5.0.1 on 2024-01-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_suppliers_delete_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='supplier_address',
            field=models.CharField(default='Default Address', max_length=255),
        ),
    ]
