# Generated by Django 5.0.1 on 2024-01-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_suppliers_supplier_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stockstatus',
            field=models.CharField(default=True, max_length=5),
        ),
    ]
