# Generated by Django 5.0.1 on 2024-01-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_stock_stockstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stockstatus',
            field=models.CharField(default='In', max_length=5),
        ),
    ]
