# Generated by Django 5.0.1 on 2024-01-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_stock_stockstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_address',
            field=models.CharField(max_length=255),
        ),
    ]
