# Generated by Django 5.0.1 on 2024-01-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('suppliername', models.TextField()),
                ('supplieremail', models.TextField()),
                ('supplierphonenum', models.CharField(max_length=12)),
                ('supplieraddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Receiver',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Suppliers',
        ),
    ]
