# Generated by Django 5.0.1 on 2024-01-11 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_supplier_delete_receiver_delete_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('productname', models.TextField()),
                ('productqty', models.IntegerField()),
                ('productprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
    ]
