# Generated by Django 5.0.1 on 2024-01-11 12:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('receiverid', models.AutoField(primary_key=True, serialize=False)),
                ('receivername', models.TextField()),
                ('receiverpositions', models.TextField()),
                ('receiveqty', models.IntegerField()),
                ('receivedate', models.DateTimeField(default=datetime.datetime.now)),
                ('receivestatus', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
