# Generated by Django 5.0.1 on 2024-01-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_inventories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventories',
            old_name='ingoingproduct',
            new_name='instock',
        ),
        migrations.RenameField(
            model_name='inventories',
            old_name='outgoingproduct',
            new_name='outgoingstock',
        ),
    ]
