# Generated by Django 5.0.1 on 2024-01-29 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_rename_ingoingproduct_inventories_instock_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventories',
        ),
    ]
