# Generated by Django 5.0.1 on 2024-01-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_delete_inventories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='receivedate',
            field=models.DateField(),
        ),
    ]
