# Generated by Django 5.0.1 on 2024-02-05 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_receiver_receivedate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
